# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2019'


variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  swigVersion: '4.0.0'
  netCoreSdkVersion: '2.2.301'
  compilerInitialization: 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'


steps:

# Installs build/run dependencies
# Sh problem: sh must not be in path, see Makefile.win.mk
- script: |
    echo 'Remove sh.exe from path'
    del "C:\Program Files\Git\usr\bin\sh.exe"
    del "C:\Program Files\Git\bin\sh.exe"
    where sh
    echo '-----------------------'
    
    cinst swig --version $(swigVersion) --no-progress
    cinst dotnetcore-sdk --version $(netCoreSdkVersion) --no-progress

    clist -lo
  displayName: Install dependencies

# Git problem: when using "C:\agents\2.155.1\externals\git\cmd\git.exe" we get problems during abseil-cpp checkout => "git: 'remote-https' is not a git command.""
- script: |
    set PATH=C:\Program Files\Git\cmd;%PATH%
    echo %PATH%
    git --info-path
    where git

    $(compilerInitialization)

    tools\make.exe detect
    tools\make third_party
  displayName: Build third_party

- script: |
    $(compilerInitialization)
    tools\make dotnet
  displayName: Build dotnet

- task: PublishPipelineArtifact@1
  inputs:
    path: $(System.DefaultWorkingDirectory)/packages
    artifact: packages