# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  swigVersion: '4.0.0'
  netCoreSdkVersion: '2.2.301'

steps:

- script: |
     set PATH=C:\Program Files\Git\cmd;%PATH%
     echo %PATH%
     del "C:\Program Files\Git\usr\bin\sh.exe"
     del "C:\Program Files\Git\bin\sh.exe"
     cinst swig --version $(swigVersion)
     cinst dotnetcore-sdk --version $(netCoreSdkVersion)
     clist -lo
     dotnet --info
     where sh
     where git
     git --info-path
     git --version
  displayName: Install dependencies

- script: |
    git --info-path
    git --version
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
    echo %PATH%
    tools\make third_party
    tools\make dotnet
  displayName: Build artifacts

- task: PublishPipelineArtifact@1
  inputs:
    path: $(System.DefaultWorkingDirectory)/packages
    artifact: packages